name: Docker Image CI

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
    branches: [ master ]
  release:
    types:
    - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      if: github.event_name == 'push'
      env:
        DOCKER_TAG_PREFIX: dev
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag nager/nager-date:$DOCKER_TAG_PREFIX-$GITHUB_RUN_NUMBER --tag nager/nager-date:latest
        docker push nager/nager-date:$DOCKER_TAG_PREFIX-$GITHUB_RUN_NUMBER
        docker push nager/nager-date:latest

    - name: Build the Docker release image
      if: github.event_name == 'release'
      run: |
        DOCKER_TAG=${GITHUB_REF##*/}
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag nager/nager-date:$DOCKER_TAG
        docker push nager/nager-date:$DOCKER_TAG
